onScreenArrow = sAnvilPointer;
offScreenArrow = sAnvilPointer;
used = false;
maxuses = 1;
audio_play_sound(snd_anvildrop,0,0, global.soundVolume);
gAnvilWeapon1 = global.null;
gAnvilWeapon2 = global.null;
gAnvilWeapon1Position = 0;
gAnvilWeapon2Position = 0;
canCollab = false;
anvilSelected = 0;